services:
  postgres:
    image: postgres:alpine
    container_name: zeroday_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zeroday
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
